services:

  real_db:
    image: postgres:17.5
    container_name: real_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5435:5432"
    volumes:
      - real_pg_data:/var/lib/postgresql/data

  real_web:
    build: .
    command: >
      sh -c "python create_tables.py && uvicorn main:app --host 0.0.0.0 --port 8000"
    container_name: real_fastapi
    volumes:
      - .:/app
    restart: always
    depends_on:
      - real_db
    env_file: .env
    ports:
      - "8001:8000"

volumes:
  real_pg_data: